import { Level } from "./Level";

export const level2: Level = {
  startFragment: [
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                          o                       ",
    "                                                  ",
    "                   xxx                            ",
    "       x  o  x                                    ",
    "       x     x                                    ",
    "       x  o  x            x                       ",
    "       x     x                                    ",
    "       !=    !            o                       ",
    "                                                  ",
    "          o              xxx                      ",
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                   xxx         xxx                ",
    "                                                  ",
    "                          o                       ",
    "                                                  ",
    "             xxx         xxx         xxx          ",
    "                                                  ",
    "                          o                       ",
    "  xxxxxxxxxxx                                     ",
    "  x         x o xxxxxxxxx   xxxxxxxxx o xx        ",
    "  x         x   x       x!!!x       x   x        x",
    "  x  @      xxxxx   o   xxxxx   o   xxxxx        x",
    "  xxxxxxx                                     xxxx",
    "        x                                     x   ",
    "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
    "                                                  ",
    "                                                  ",
  ],
  endFragment: [
    "                                              !",
    "                                              !",
    "                                              !",
    "                                              !",
    "                                              !",
    "      ooo        ooo                ooo       !",
    "      xxx        xxx                xxx       !",
    "     xx!xx      xx!xx    o         xx!xx      !",
    "     x!!!x      x!!!x    xx        x!!!x      !",
    "     xx!xx      xx!xx              xx!xxx     !",
    "      xvx        xvx                xvx       !",
    "                             xx               !",
    "                                             o!",
    "                            o               xx!",
    "                           xx                 !",
    "                                              !",
    "                      o                       !",
    "                     xx                       !",
    "                                              !",
    "                o                             !",
    "               xx                             !",
    "                                              !",
    "          o                                   !",
    "         xx                                   !",
    "                                              !",
    "                                             !!",
    "   xx                                       !!!",
    "                                           !!!!",
    "                                          !!!!!",
    "x                                        !!!!!!",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  ],
};
