export const START_MAP_FRAGMENT_ROWS = [
  "                                                                       ",
  "                                                                       ",
  "                                                                       ",
  "                                                                       ",
  "                                                                       ",
  "                                                                       ",
  "                                      x!!x                             ",
  "                                      x!!x                             ",
  "                                      x!!xxxxxxxxxx                    ",
  "                                      xx!!!!!!!!!!xx                   ",
  "                                       xxxxxxxxxx!!x                   ",
  "                                                xx!x                   ",
  "                                                 x!x                   ",
  "                                                 xvx                   ",
  "                                                                       ",
  "                                                                       ",
  "                                                                       ",
  "                                               x     x                 ",
  "                                               x     x                 ",
  "                                               x     x                 ",
  "                                               x     x                 ",
  "                                               xx    x             xx  ",
  "                                               x     x      o  o       ",
  "               xxxxxxx        xxx   xxx        x     x                 ",
  "              xx     xx         x   x          x     x     xxxxxx      ",
  "             xx       xx        x o x          x    xx                 ",
  "     @       x         x        x   x          x     x                 ",
  "    xxx      x         x        x   x          x     x                 ",
  "    x x      x         x       xx o xx         x     x                 ",
  "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!       ",
  "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!       ",
  "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !       ",
  "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !       ",
  "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !       ",
  "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !       ",
  "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !       ",
];

export const END_MAP_FRAGMENT_ROWS = [
  "                  ",
  "                  ",
  "                  ",
  "              x   ",
  "              x   ",
  "              x   ",
  "              x   ",
  "              x   ",
  "             ox   ",
  "             xx   ",
  "        x    xx   ",
  "             xx   ",
  "             xx   ",
  "             xx   ",
  "           xxxx   ",
  "            xxx   ",
  "       x    xxx   ",
  "            xxx   ",
  "            xxx   ",
  "          xxxxx   ",
  "            xxx   ",
  "      x     xxx   ",
  "            xxx   ",
  "            xxx   ",
  "            xxx   ",
  "         xxxxxx   ",
  "           xxxx   ",
  "     x     xxxx   ",
  "           xxox   ",
  "xxx        xxox   ",
  "  x=          x   ",
  "  x    xx     x   ",
  "  x           x   ",
  "  x           x   ",
  "  x  xxxxx   xx   ",
  "  x!!x   x!!!x    ",
];
